/**
 * RUNTIME_ASSETS is the canonical set of daemon runtime binaries the wasm client
 * loads at runtime, resolved against runtimeBaseUrl. They are built by
 * wavelength (`make wasm-wallet`) and version-locked to the embedded wavewalletdk
 * daemon, so they ship together and must be hosted side by side at a single base
 * URL.
 *
 * This is the single source of truth for the self-host instructions, and the
 * set the release archive is expected to carry. The standalone worker
 * (wavewalletdk-worker.js) cannot
 * import this module, so it mirrors these names literally; keep the two in sync.
 *
 * The version of the asset set (RUNTIME_MANIFEST_VERSION) lives in core, next
 * to the generated daemon types it is paired with.
 */
export const RUNTIME_ASSETS = {
  wasm: 'wavewalletdk.wasm',
  wasmGz: 'wavewalletdk.wasm.gz',
  wasmExec: 'wasm_exec.js',
  sqliteBridge: 'sqlite-bridge.js',
  sqliteWorker: 'sqlite-worker.js',
  sqlite: 'sqlite3.js',
  sqliteWasm: 'sqlite3.wasm',
  sqliteOpfsProxy: 'sqlite3-opfs-async-proxy.js',
} as const;

/**
 * RUNTIME_ASSET_FILES is the flat list of every runtime binary that must be
 * hosted together at runtimeBaseUrl.
 */
export const RUNTIME_ASSET_FILES: readonly string[] =
  Object.values(RUNTIME_ASSETS);

/**
 * RUNTIME_ASSET_DIGESTS pins the SHA-256 digest (SRI format,
 * `sha256-<base64>`) of every file in the runtime asset set published for
 * RUNTIME_MANIFEST_VERSION. The web transport verifies the wasm binary and
 * the bootstrap scripts it executes against this table before running them;
 * the full table is exported so integrators can also verify their hosted set
 * at deploy time.
 *
 * Generated by `pnpm gen:runtime-digests` from a staged asset set; do not
 * edit by hand. CI's runtime-pin job fails when this table drifts from the
 * assets attached to the pinned wavelength release.
 */
export const RUNTIME_ASSET_DIGESTS: Readonly<Record<string, string>> = {
  'wavewalletdk.wasm': 'sha256-FlaDCwfNtrBPNa4Jw5o96BRWn00HQEm+PwolBTcMiaI=',
  'wavewalletdk.wasm.gz': 'sha256-jkLzhJPireXwaeUwiHwQCyTLXaQE38ew61TtBkzXpTk=',
  'wasm_exec.js': 'sha256-DJSfSZb5qJaY5LXFht4yJJw7abe6rbZNIgBzzASsuhQ=',
  'sqlite-bridge.js': 'sha256-WvlgAYAAemwc55zlPx1L2YPDyrx1J2HXe0Sf5RKhcGY=',
  'sqlite-worker.js': 'sha256-ddNoKARRiAtefqxLvOfRotkLFUZzStZ4PZ2HEt3aN+k=',
  'sqlite3.js': 'sha256-zrflgDHuusFRxaA3S8i7gt/2IhusVZR2YgEafLSFusk=',
  'sqlite3.wasm': 'sha256-TdUvrfXXbgq+424HRBuqK1OnYNFZHTuhIA7KiOEegsY=',
  'sqlite3-opfs-async-proxy.js': 'sha256-TqK8vXFbDVYIn8hx6iQfjFmF2GadHd7Kq01WqNqAbOk=',
};
